# Kafka 生产者、消费者和管理者 所需的连接配置
# 如果是本地安装, 请更改为127.0.0.1:9092, 默认的端口是9092, 即broker的端口
bootstrap:
  servers: 192.168.2.158:9092

# 安全协议
# PLAINTEXT: 最基本的机制，使用明文用户名和密码进行身份验证，安全性较低
# SSL: 使用 SSL/TLS 进行加密。
# SASL_PLAINTEXT: 使用 SASL 认证和明文传输。
# SASL_SSL: 使用 SASL 认证和 SSL/TLS 加密。
# security.protocol=SASL_SSL

# 认证机制
# 该配置选项用于指定 Kafka 服务器支持的 SASL (Simple Authentication and Security Layer) 认证机制。多个机制可以使用逗号分隔
# PLAIN: 使用明文用户名和密码进行认证。
# GSSAPI: 使用 Kerberos 进行认证。
# SCRAM: 使用 SCRAM-SHA-256 或 SCRAM-SHA-512 进行认证

# Kafka生产者防止数据丢失的最佳实践
acks: all

# 在 1.7 之前的 librdkafka 客户端中提高可用性的最佳实践
# session.timeout.ms=45000
